// Mock data for the platform — replace with real data/API later

export const RANKS = [
  { level: 1, title: "Neophyte", xpRequired: 0, icon: "🛡️" },
  { level: 2, title: "Battle Brother", xpRequired: 500, icon: "⚔️" },
  { level: 3, title: "Veteran", xpRequired: 1500, icon: "🎖️" },
  { level: 4, title: "Sergeant", xpRequired: 3000, icon: "🗡️" },
  { level: 5, title: "Lieutenant", xpRequired: 5000, icon: "🏅" },
  { level: 6, title: "Captain", xpRequired: 8000, icon: "👑" },
  { level: 7, title: "Chapter Master", xpRequired: 12000, icon: "🔥" },
  { level: 8, title: "Warmaster", xpRequired: 20000, icon: "⭐" },
];

export const FACTIONS = [
  "Space Marines",
  "Aeldari",
  "Tyranids",
  "Death Guard",
  "Orks",
  "Necrons",
  "Adeptus Mechanicus",
  "Adepta Sororitas",
  "T'au Empire",
  "Chaos Space Marines",
  "Imperial Knights",
  "Chaos Daemons",
  "Drukhari",
  "Genestealer Cults",
  "Thousand Sons",
  "World Eaters",
  "Custodes",
  "Votann",
  "Grey Knights",
  "Agents of the Imperium",
];

export const ACHIEVEMENTS = [
  {
    id: "first-blood",
    title: "First Blood",
    description: "Watch your first video",
    xp: 50,
    icon: "🩸",
    unlocked: true,
  },
  {
    id: "faction-recruit",
    title: "Faction Recruit",
    description: "Complete a faction focus series",
    xp: 200,
    icon: "🏴",
    unlocked: true,
  },
  {
    id: "tactician",
    title: "Tactician",
    description: "Watch 10 strategy videos",
    xp: 300,
    icon: "🧠",
    unlocked: true,
  },
  {
    id: "war-council",
    title: "War Council",
    description: "Attend your first group coaching session",
    xp: 500,
    icon: "🫂",
    unlocked: false,
  },
  {
    id: "champions-wisdom",
    title: "Champion's Wisdom",
    description: "Complete a 1-on-1 session with Sacco",
    xp: 1000,
    icon: "🏆",
    unlocked: false,
  },
  {
    id: "master-class",
    title: "Master Class Graduate",
    description: "Complete all videos in a masterclass",
    xp: 750,
    icon: "🎓",
    unlocked: false,
  },
  {
    id: "streak-warrior",
    title: "Streak Warrior",
    description: "7-day login streak",
    xp: 400,
    icon: "🔥",
    unlocked: false,
  },
  {
    id: "polyglot",
    title: "The Polyglot",
    description: "Watch content in 3 different languages",
    xp: 200,
    icon: "🌍",
    unlocked: false,
  },
];

export const MOCK_USER = {
  name: "Battle Brother Alex",
  faction: "Aeldari",
  rank: RANKS[2], // Veteran
  xp: 2150,
  nextRankXp: 3000,
  level: 3,
  joinDate: "2025-11-15",
  videosWatched: 24,
  sessionsAttended: 2,
  streakDays: 5,
  achievements: ACHIEVEMENTS,
};

export const CONTENT_ITEMS = [
  {
    id: "1",
    title: "Aeldari in the Current Meta",
    type: "Faction Focus",
    coach: "Sacco",
    coachTitle: "2x World Champion",
    duration: "32 min",
    thumbnail: "/thumbnails/aeldari.jpg",
    premium: false,
    languages: ["EN", "FR", "ES", "DE"],
    views: 12400,
    xpReward: 50,
  },
  {
    id: "2",
    title: "Space Marines: Competitive Guide",
    type: "Masterclass",
    coach: "Sacco",
    coachTitle: "2x World Champion",
    duration: "1h 45min",
    thumbnail: "/thumbnails/sm.jpg",
    premium: true,
    languages: ["EN", "FR", "ES"],
    views: 8200,
    xpReward: 150,
  },
  {
    id: "3",
    title: "Tournament Report: LGT 2025",
    type: "Tournament Report",
    coach: "Sacco",
    coachTitle: "2x World Champion",
    duration: "58 min",
    thumbnail: "/thumbnails/lgt.jpg",
    premium: true,
    languages: ["EN", "FR"],
    views: 6100,
    xpReward: 100,
  },
  {
    id: "4",
    title: "How to Build a Tournament List",
    type: "Strategy",
    coach: "Sacco",
    coachTitle: "2x World Champion",
    duration: "45 min",
    thumbnail: "/thumbnails/listbuilding.jpg",
    premium: false,
    languages: ["EN", "FR", "ES", "DE", "IT"],
    views: 18700,
    xpReward: 75,
  },
  {
    id: "5",
    title: "Tyranids Deep Dive",
    type: "Faction Focus",
    coach: "Guest Coach",
    coachTitle: "ETC Champion",
    duration: "40 min",
    thumbnail: "/thumbnails/tyranids.jpg",
    premium: false,
    languages: ["EN", "FR"],
    views: 9300,
    xpReward: 50,
  },
  {
    id: "6",
    title: "Advanced Deployment Tactics",
    type: "Masterclass",
    coach: "Sacco",
    coachTitle: "2x World Champion",
    duration: "1h 20min",
    thumbnail: "/thumbnails/deployment.jpg",
    premium: true,
    languages: ["EN", "FR", "ES"],
    views: 5400,
    xpReward: 150,
  },
];

export const COACHING_SESSIONS = [
  {
    id: "g1",
    type: "group",
    title: "Meta Breakdown: April 2026",
    coach: "Sacco",
    coachTitle: "2x World Champion",
    date: "2026-04-15",
    time: "19:00 CET",
    spotsTotal: 20,
    spotsTaken: 14,
    price: 79,
    description:
      "Live group session breaking down the current competitive meta. Bring your lists and questions!",
    xpReward: 300,
  },
  {
    id: "g2",
    type: "group",
    title: "List Doctor: Fix Your Army",
    coach: "Sacco",
    coachTitle: "2x World Champion",
    date: "2026-04-22",
    time: "20:00 CET",
    spotsTotal: 15,
    spotsTaken: 11,
    price: 59,
    description:
      "Submit your army list and get live feedback from a world champion. Limited spots for maximum value.",
    xpReward: 300,
  },
  {
    id: "g3",
    type: "group",
    title: "Tournament Prep Bootcamp",
    coach: "Sacco",
    coachTitle: "2x World Champion",
    date: "2026-05-01",
    time: "18:00 CET",
    spotsTotal: 20,
    spotsTaken: 7,
    price: 99,
    description:
      "Intensive 2-hour session to get you tournament-ready. Covers list building, deployment, and in-game decision making.",
    xpReward: 500,
  },
  {
    id: "p1",
    type: "private",
    title: "1-on-1 with Sacco",
    coach: "Sacco",
    coachTitle: "2x World Champion",
    price: 149,
    description:
      "60 minutes of personal coaching with a 2x World Champion. Tailored to your level, your faction, your goals.",
    xpReward: 500,
  },
  {
    id: "p2",
    type: "private",
    title: "1-on-1 with Guest Coach",
    coach: "Various",
    coachTitle: "ETC / GT Champions",
    price: 99,
    description:
      "60 minutes of coaching with top-tier competitive players. Faction specialists available.",
    xpReward: 400,
  },
];
